#!/bin/bash

if [[ $# != 2 ]]
then
    echo "Usage: $0 resistor-value current_range {low|high}" 1>&2
    exit 1
fi

R=$1
CR=$2

for v in 1.2 1.5 2.4 3.0 3.2 3.6 3.7 4.2 4.5
do
    echo 6 k $v $R / 1000 \* p | dc
    python3 -m battlab -w 2 -d 2 -v $v -c $CR
done
